### PR TITLE
Enable CRIU support by default on ppc64le builds

### PR DESCRIPTION
**Pull request by ymanton**

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity zlinux jdknext

**Comment by tajila** [comment]
jenkins test sanity plinux jdknext

**Comment by tajila** [comment]
@0xdaryl

**Comment by keithc-ca** [comment]
The merge conflict will need to be resolved.

**Comment by tajila** [comment]
@ymanton Can you please rebase this, I think the releng team has updated the external machines

**Comment by ymanton** [comment]
Rebased.

**Comment by tajila** [comment]
jenkins test sanity plinux jdknext

**Comment by tajila** [comment]
jenkins test sanity plinux jdknext

**Pull request merged**
