### PR TITLE
Update get_source.sh

### PR DESCRIPTION
**Pull request by keithc-ca**
* improve feedback for invalid arguments
* improve feedback for cloning steps
* remove support for non-standard options (unused since [openj9#19387](https://github.com/eclipse-openj9/openj9#19387))
* remove unused variables

### CODE REVIEW

**Comment by pshipton** [comment]
We should open a doc issue to have a release note that `--openssl-repo` and `--openssl-version` are removed, and what they are replaced with.

**Comment by pshipton** [comment]
Also it would be worth announcing this on Slack, since anyone doing their own builds may be surprised by the change.

**Comment by keithc-ca** [comment]
There's nothing in openj9-docs that currently mentions those (old) options; and https://github.com/eclipse-openj9/openj9/pull/19387 updated the documentation in openj9. Do you not think that's sufficient?

**Comment by keithc-ca** [comment]
Slack announcement: https://openj9.slack.com/archives/CDS7QE9HB/p1714150601939569.

**Comment by pshipton** [comment]
Usually when there is a change there is a release note to give notice of the change. I can amend my statement: We should open a doc issue to have a release note that --openssl-repo and --openssl-version are removed, **and refer to the updated build instructions.**

**Comment by pshipton** [comment]
jenkins compile amac jdknext

**Comment by keithc-ca** [comment]
> Usually when there is a change there is a release note to give notice of the change

Yes, but so far we've only been documenting changes that impact users of the SDK. This isn't such a change.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
I'm fine if it just goes into the OpenJ9 release notes document and not the User Guide. The doc issue can mention that.
https://github.com/eclipse-openj9/openj9/tree/master/doc/release-notes

**Comment by pshipton** [comment]
I got what I needed from the build, which created the JVM, but failed to upload afterwards.

**Comment by keithc-ca** [comment]
I created https://github.com/eclipse-openj9/openj9/pull/19392, but even there I couldn't find an earlier example of pointing out changes to instructions for building a JDK.

**Pull request merged**
