### PR TITLE
Merge openj9-staging into openj9

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
Usually, the `openj9-staging` is promoted via abuilds, it could be merged into `openj9` branch manually if an incompatible openj9 change was explicitly introduced for `openj9-staging` branch.
@keithc-ca What's the occasion for this PR?

**Comment by keithc-ca** [comment]
It's mostly a matter of hygiene: The automatic merge from a successful abuild would create a commit authored by genie-openj9 (like e.g. ded992abccc234297c7ec55ecbc0cfcd3cd78bfc). My preference is for a regular merge.

**Comment by JasonFengJ9** [comment]
> It's mostly a matter of hygiene: The automatic merge from a successful abuild would create a commit authored by genie-openj9 (like e.g. https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ded992abccc234297c7ec55ecbc0cfcd3cd78bfc). My preference is for a regular merge.

Is this going to be a regular practice onwards?

**Comment by keithc-ca** [comment]
> Is this going to be a regular practice onwards?

No, I don't think this should be done regularly. If you don't think this appropriate, simply close the pull request, and we'll live with the merge by genie-openj9.

**Comment by JasonFengJ9** [comment]
Thanks for the clarification. 
Closing this to allow abuild promotion.

**Pull request closed without merging**
