### PR TITLE
Rename CacheNameClass to ClassByNameCache

### PR DESCRIPTION
**Pull request by pshipton**
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/388
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/99

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile amac jdknext

**Review by keithc-ca — COMMENTED** [review]
Can you please clean up the trailing whitespace (like you did in ibmruntimes/openj9-openjdk-jdk17#99)?

**Comment by pshipton** [comment]
PR build https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDKnext/44/

**Comment by pshipton** [comment]
Updated. Does the Line Endings Check job not work?

**Comment by keithc-ca** [comment]
> Updated. Does the Line Endings Check job not work?

The line-endings check only considers lines changed by a pull request.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
