### PR TITLE
Revert "Remove unused targets openj9-{jdk,jre}-image"

### PR DESCRIPTION
**Pull request by groeges**
This reverts commit 6d29baf3d7557c280f0fcfc1aaedab46fdbb680f.

Signed-off-by: Steve Groeger GROEGES@uk.ibm.com

### CODE REVIEW

**Comment by pshipton** [comment]
I expect @keithc-ca will make some comments about this.

**Comment by keithc-ca** [comment]
Simply reverting this will leave things in a state where builds will fail due to the absence of the `jre-image` target which was a prerequisite of `openj9-jre-image` which in turn is required by `product-images`.

I suspect we only need to add whatever is missing to `generated_target_rules_build` or perhaps add the dependency `product-images : j9vm-build` in closed/Main.gmk.

**Comment by groeges** [comment]
Even if I revert the changes the issue still occurs. 
Closing this PR and will open another one later when we know what the actual issue is.

**Comment by keithc-ca** [comment]
I think https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/10 fixes the problem this tried to address.

**Comment by andrew-m-leonard** [comment]
@keithc-ca one thing to verify once this is fixed up, is that jlink still works correctly...? the original targets for separate jre/jdk image targets was related to jlink not creating valid JREs.., it would be worth validating that still works too...

**Comment by keithc-ca** [comment]
I did validate that with this fix, jlink yields a working package.

**Pull request closed without merging**
