### PR TITLE
Enable cmake for Windows by default

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity win jdknext

**Comment by pshipton** [comment]
jenkins test sanity,sanity.openjdk win jdknext

**Review by keithc-ca — APPROVED** [review]

**Comment by pshipton** [comment]
The openjdk failure doesn't seem related to cmake. We aren't running these tests on jdk17 atm, so I will start grinders to double check this failure shortly.

**Comment by pshipton** [comment]
The same failure occurs without cmake
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1503/

**Pull request merged**
