### PR TITLE
Enable cmake by default on linux and mac platforms

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux jdknext

**Comment by pshipton** [comment]
I'm assuming this will work considering jdk16 does, I'm not going to bother with more testing.

**Comment by pshipton** [comment]
@dnakamura fyi

**Comment by pshipton** [comment]
I've set this back to draft because a jdk17 acceptance build is going to run, and merging this will affect it's promotion.

**Review by keithc-ca — APPROVED** [review]

**Comment by pshipton** [comment]
The jdk17 acceptance build has promoted now.

**Pull request merged**
