### PR TITLE
In Thread.start(ThreadContainer) use this.started for clarity

### PR DESCRIPTION
**Pull request by pshipton**
The method has a local variable called started as well.

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
jenkins test sanity amac jdknext

**Comment by pshipton** [comment]
Do we run sanity internally? We don't run any jdk20 testing at OpenJ9 yet, so not sure how it will go.

**Comment by JasonFengJ9** [comment]
> Do we run sanity internally?

No, probably we are going to hit some missing configuration files.

**Review by JasonFengJ9 — APPROVED** [review]
The test has been going far enough to verify this PR sanity.

**Pull request merged**
