### PR TITLE
Merge master HEAD into openj9-staging

### PR DESCRIPTION
**Pull request by keithc-ca**
Resolve conflicts with:
* [8308398: Move SunEC crypto provider into java.base](f106832f6e9a8a663b5470f48460f8cfc6c2959d)

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
>Merge master HEAD into openj9-staging

Pls change this PR target branch from `openj9` to `openj9-staging`.

**Comment by keithc-ca** [comment]
> Pls change this PR target branch from `openj9` to `openj9-staging`.

Sorry for that. Done.

**Comment by JasonFengJ9** [comment]
A couple of questions:

> 	src/jdk.crypto.ec/share/classes/sun/security/ec/ECKeyPairGenerator.java
	src/jdk.crypto.ec/share/classes/sun/security/ec/ECPrivateKeyImpl.java
	src/jdk.crypto.ec/share/classes/sun/security/ec/ECPublicKeyImpl.java
	src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java
	src/jdk.crypto.ec/share/classes/sun/security/ec/XDHPublicKeyImpl.java

did your script show the `CONFLICT` on these files?

`closed/openjdk-tag.gmk` wasn't updated to `jdk-22+7`, or you were running against an earlier `master` branch?

**Comment by keithc-ca** [comment]
> A couple of questions:
> 
> > src/jdk.crypto.ec/share/classes/sun/security/ec/ECKeyPairGenerator.java
> > src/jdk.crypto.ec/share/classes/sun/security/ec/ECPrivateKeyImpl.java
> > src/jdk.crypto.ec/share/classes/sun/security/ec/ECPublicKeyImpl.java
> > src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java
> > src/jdk.crypto.ec/share/classes/sun/security/ec/XDHPublicKeyImpl.java
> 
> did your script show the `CONFLICT` on these files?

Builds will fail if those files are not moved to java.base (with the rest of jdk.crypto.ec code).

> `closed/openjdk-tag.gmk` wasn't updated to `jdk-22+7`, or you were running against an earlier `master` branch?

That tag was not present when I created this change. I can update this to include that tag update and more recent changes from upstream if you like.

**Comment by JasonFengJ9** [comment]
> Builds will fail if those files are not moved to java.base (with the rest of jdk.crypto.ec code).

In my run, the files in question are moved into `java.base` folder by git merge, only saw one conflict
```
CONFLICT (content): Merge conflict in src/java.base/share/lib/security/default.policy
```

**Comment by keithc-ca** [comment]
Sorry, I thought you had asked about the files within `closed/src/jdk.crypto.ec/share/classes`. I did see (modify vs. move) conflicts for the files in `src/jdk.crypto.ec/share/classes`.

**Comment by JasonFengJ9** [comment]
> I did see (modify vs. move) conflicts for the files in src/jdk.crypto.ec/share/classes

It seems an issue with the script run, the [nightly merging job](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJDK%20Team%20-%20Jobs/job/Merge%20Master%20to%20openj9-staging%20Jobs/job/Merge-to-Staging-JDKNext/1374/console) just had one CONFLICT as well.
```
23:19:43  CONFLICT (content): Merge conflict in src/java.base/share/lib/security/default.policy
```
Please re-run and pull more recent changes from upstream.

**Comment by keithc-ca** [comment]
> Please re-run and pull more recent changes from upstream.

I see the openj9-staging branch moved on to e5ceea59ab6c973c7c3353b611750b1c4497ffe5; so this will need another pass.

**Comment by keithc-ca** [comment]
I don't understand why github still believes there are conflicts; openj9-staging (e5ceea59ab6c973c7c3353b611750b1c4497ffe5) is an ancestor or the head of my merge branch (40742f25e5caad701a49a35ac1e11b01b4dfd17a):
```sh
$ git merge-base --is-ancestor e5ceea59ab6c973c7c3353b611750b1c4497ffe5 40742f25e5caad701a49a35ac1e11b01b4dfd17a && echo yes
yes
```

**Comment by keithc-ca** [comment]
Closing this in favour of #634 which proposes to merge the same SHA into the same branch, without conflict.

**Pull request closed without merging**
