### PR TITLE
Export the CONFIG_SHELL variable

### PR DESCRIPTION
**Pull request by dnakamura**
This variable identifies which shell to use when running future instances
of configure

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
This, along with eclipse/omr#2647 should resolve eclipse/omr#2567

**Comment by AdamBrousseau** [comment]
Jenkins copyright check
Jenkins line endings check
Jenkins signed off by check

**Comment by AdamBrousseau** [comment]
checks are failing due to bug in SCM/Git plugin. I will follow up

**Comment by AdamBrousseau** [comment]
eclipse/openj9#2154
Jenkins copyright check
Jenkins line endings check
Jenkins signed off by check

**Pull request merged**
