### PR TITLE
Add Continuation Allocation Profiling option

### PR DESCRIPTION
**Pull request by fengxue-IS**
Depends: https://github.com/eclipse-openj9/openj9/pull/17704

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
jenkins compile alinux64 jdknext

**Comment by tajila** [comment]
do you make one for jdk21?

**Comment by fengxue-IS** [comment]
> do you make one for jdk21?

added https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/14

**Comment by tajila** [comment]
unrelated failure

**Pull request merged**
