### PR TITLE
Restore ability to build with OpenJ9

### PR DESCRIPTION
**Pull request by keithc-ca**
This is a replay of ibmruntimes/openj9-openjdk-jdk15#5; it depends on eclipse/openj9#10000.
* don't try to build test-image-libtest-jtreg-native
* use OPENJDK_TARGET_OS instead of HOTSPOT_TARGET_OS

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins compile aix,osx,plinux,xlinux,zlinux,win jdknext depends eclipse/openj9#10000

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdknext depends eclipse/openj9#10000

**Comment by pshipton** [comment]
The AIX failure is https://github.com/eclipse/openj9/issues/9997

**Comment by pshipton** [comment]
plinux build worked, but is failing to upload the JDK to UNB.
`sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by pshipton** [comment]
I'll merge the changes, but not promote jdknext openj9-staging until we resolve the test failures https://github.com/eclipse/openj9/issues/10003

**Pull request merged**
