### PR TITLE
Revert StringConcatFactory.java commits

### PR DESCRIPTION
**Pull request by babsingh**
- Revert "8246632: StringConcatFactory::makeConcatWithConstants ..."
- Revert "8246152: Improve String concat bootstrapping"

The above commits are reverted because of the `MethodHandle.rebind` dependency which can't be supported in OpenJ9 until OpenJ9 adopts the OpenJDK MethodHandles. `rebind` returns a `BoundMethodHandle` which is not currently supported in OpenJ9. 

`StringConcatFactory` also introduced a dependency on `MethodHandle.viewAsType`, which is not currently supported in OpenJ9.

Reverting the above two commits will allow us to temporarily build JDK15 with OpenJ9.

Once OpenJ9 adopts the OpenJDK MethodHandles, the above reverts can be undone.

Fixes: https://github.com/eclipse/openj9/issues/9771

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
fyi @DanHeidinga

**Comment by pshipton** [comment]
@babneet there are conflicts now.

**Comment by pshipton** [comment]
If we merge these reverts, it may cause an ongoing effort to fix merge conflicts (revert more changes) as we get new changes from OpenJDK.

**Comment by babsingh** [comment]
Closing. This PR being replaced with https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/215 (alternate, small patch fix).

**Pull request closed without merging**
