### PR TITLE
Add dependency module java.management.rmi for ibm.healthcenter

### PR DESCRIPTION
**Pull request by sharanpatil123**
This change is to avoid HealthCenterException thrown when HC client using healthcenter API’s tries to connect to target JVM running on Semeru JDK11+

Exception details when Semeru Java11 client tries connecting to Java 11 HC target

Exception in thread "main" com.ibm.java.diagnostics.healthcenter.api.HealthCenterException: Unable to connect to agent, check authentication details are correct
at ibm.healthcenter/com.ibm.java.diagnostics.healthcenter.api.factory.HealthCenterFactory.connect(Unknown Source)
at WorkingCase.main(WorkingCase.java:29)

### CODE REVIEW

**Comment by sharanpatil123** [comment]
While debugging this issue, we noticed below module dependency warning,

```WARNING: An exception occurred checking port 1972 for a Health Center agent. The exception was: java.lang.IllegalAccessError: Class com/ibm/java/diagnostics/healthcenter/impl/jmx/JMXAgentConnectionManager$ConnectorThread(ibm.healthcenter) can not access class javax/management/remote/rmi/RMIServer(java.management.rmi) because module ibm.healthcenter does not read module java.management.rmi```

java.lang.IllegalAccessError: Class com/ibm/java/diagnostics/healthcenter/impl/jmx/JMXAgentConnectionManager$ConnectorThread(ibm.healthcenter) can not access class javax/management/remote/rmi/RMIServer(java.management.rmi) because module ibm.healthcenter does not read module java.management.rmi
at ibm.healthcenter/com.ibm.java.diagnostics.healthcenter.impl.jmx.JMXAgentConnectionManager$ConnectorThread.initialiseMbeanConnectorByRMI(Unknown Source)
at ibm.healthcenter/com.ibm.java.diagnostics.healthcenter.impl.jmx.JMXAgentConnectionManager$ConnectorThread.run(Unknown Source)

**Review by keithc-ca — CHANGES_REQUESTED** [review]
Please squash and update the commit message: "API's" should be "APIs" and the sentence should end with a period.

**Comment by sharanpatil123** [comment]
Thanks @keithc-ca, squashed with updated commit message.

Once it is merged, can i open backport PRs in JDK 11/17/21?

**Comment by keithc-ca** [comment]
> Once it is merged, can i open backport PRs in JDK 11/17/21?

Yes, but the order is JDK 23, 21, 17, 11.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
