### PR TITLE
Support new properties in OpenJ9PropsExt

### PR DESCRIPTION
**Pull request by keithc-ca**
`systemd.support` introduced upstream in
* [8333446: Add tests for hierarchical container support](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/e1e7dc5afccbbef06ba95b2cc9e4680c3bbe640c)

`jlink.packagedModules` introduced upstream in
* [8311302: Implement JEP 493: Linking Run-Time Images without JMODs](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/4c1b0e03d35fb85dc7b8d372af5c1cc0edc55f36)

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity.openjdk amac jdknext

**Comment by pshipton** [comment]
jenkins compile zlinux jdknext

**Comment by pshipton** [comment]
The PR builds are useless.

Tested jdk/modules/etc/JmodExcludedFiles.java on amac via grinder.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3973
```
11:55:58  /Users/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/../../closed/test/jtreg-ext/requires/OpenJ9PropsExt.java:75: error: cannot find symbol
11:55:58              return Path.of(System.getProperty("java.home"), "jmods").toFile().exists();
11:55:58                     ^
11:55:58    symbol:   variable Path
11:55:58    location: class OpenJ9PropsExt
```

**Comment by keithc-ca** [comment]
Added missing import; launched new grinder: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3974.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
