### PR TITLE
Merge master HEAD into openj9-staging

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Conflicts:
```
	make/autoconf/jdk-version.m4
	make/conf/version-numbers.conf
	src/java.base/share/classes/java/lang/String.java
	src/java.base/share/classes/java/lang/Thread.java
	src/java.base/share/classes/java/lang/foreign/VaList.java
	src/java.base/share/classes/jdk/internal/foreign/CABI.java
	src/java.base/share/classes/jdk/internal/foreign/PlatformLayouts.java
	src/java.base/share/classes/jdk/internal/foreign/SystemLookup.java
	src/java.base/share/classes/jdk/internal/foreign/abi/AbstractLinker.java
	src/java.base/share/classes/jdk/internal/foreign/abi/SharedUtils.java
	src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java
	src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java
	src/java.base/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java
	src/java.base/unix/classes/java/lang/ProcessEnvironment.java
	src/jdk.management.agent/share/conf/management.properties
	test/jdk/java/foreign/CallGeneratorHelper.java
	test/jdk/java/foreign/LibraryLookupTest.java
	test/jdk/java/foreign/NativeTestHelper.java
	test/jdk/java/foreign/SafeFunctionAccessTest.java
	test/jdk/java/foreign/StdLibTest.java
	test/jdk/java/foreign/TestClassLoaderFindNative.java
	test/jdk/java/foreign/TestDowncallScope.java
	test/jdk/java/foreign/TestDowncallStack.java
	test/jdk/java/foreign/TestFunctionDescriptor.java
	test/jdk/java/foreign/TestHeapAlignment.java
	test/jdk/java/foreign/TestMatrix.java
	test/jdk/java/foreign/TestNULLAddress.java
	test/jdk/java/foreign/TestNative.java
	test/jdk/java/foreign/TestNulls.java
	test/jdk/java/foreign/TestScopedOperations.java
	test/jdk/java/foreign/TestSegments.java
	test/jdk/java/foreign/TestStringEncoding.java
	test/jdk/java/foreign/TestUpcallAsync.java
	test/jdk/java/foreign/TestUpcallException.java
	test/jdk/java/foreign/TestUpcallHighArity.java
	test/jdk/java/foreign/TestUpcallScope.java
	test/jdk/java/foreign/TestUpcallStack.java
	test/jdk/java/foreign/TestUpcallStructScope.java
	test/jdk/java/foreign/TestVarArgs.java
	test/jdk/java/foreign/enablenativeaccess/TestEnableNativeAccess.java
	test/jdk/java/foreign/handles/Driver.java
	test/jdk/java/foreign/loaderLookup/TestLoaderLookup.java
	test/jdk/java/foreign/loaderLookup/TestLoaderLookupJNI.java
	test/jdk/java/foreign/valist/VaListTest.java
```

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
[8296477: Foreign linker implementation update following JEP 434](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/531/commits/16b01abab6c3faf9c7727b1098dad8731e1da735) brings a large change and the build failed to compile:
```
/Users/jasonfeng/ivm/exts/ext-merge-conflict/jdkNext-1206/testbuildV2/build/macosx-aarch64-server-release/support/j9jcl/java.base/share/classes/jdk/internal/foreign/abi/DowncallLinker.java:27: error: cannot find symbol
import java.lang.foreign.Addressable;
                        ^
  symbol:   class Addressable
  location: package java.lang.foreign
/Users/jasonfeng/ivm/exts/ext-merge-conflict/jdkNext-1206/testbuildV2/build/macosx-aarch64-server-release/support/j9jcl/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java:29: error: cannot find symbol
import java.lang.foreign.MemorySession;
                        ^
  symbol:   class MemorySession
  location: package java.lang.foreign
/Users/jasonfeng/ivm/exts/ext-merge-conflict/jdkNext-1206/testbuildV2/build/macosx-aarch64-server-release/support/j9jcl/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java:43: error: cannot find symbol
	UpcallLinker(MethodHandle target, MethodType mt, FunctionDescriptor cDesc, MemorySession session) {
```

It seems OpenJ9 has to adopt these changes before it can be merged.

FYI @ChengJin01 @tajila

**Comment by ChengJin01** [comment]
This is the new API changes for https://github.com/eclipse-openj9/openj9/issues/16329 (JEP434) for Java 20.  So merging needs to be hold off till the code related is modified to adapt to the feature.

**Comment by ChengJin01** [comment]
We might need to evaluate how many they made in OpenJDK to support FFI JEP434 in Java20 but it looks like there are quite a lot of changes, in which case it will take a couple of weeks or 1/2 months to get everything in OpenJDK & OpenJ9 set up for the new changes given we are currently still working on issues related to FFI and have no time spent on this new feature.

**Comment by JasonFengJ9** [comment]
@ChengJin01 a similar change as https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12 is required here.

FYI @keithc-ca

**Comment by ChengJin01** [comment]
@JasonFengJ9, there are a bunch of compilation errors with Access.java as follows:
```
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:69: error: Access is not abstract and does not override abstract method setExtentLocalBindings(Object) in JavaLangAccess
final class Access implements JavaLangAccess {
      ^
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:455: error: cannot find symbol
		return Thread.scopedValueCache();
		             ^
  symbol:   method scopedValueCache()
  location: class Thread
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:459: error: cannot find symbol
		Thread.setScopedValueCache(cache);
		      ^
  symbol:   method setScopedValueCache(Object[])
  location: class Thread
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:463: error: cannot find symbol
		return Thread.scopedValueBindings();
		             ^
  symbol:   method scopedValueBindings()
  location: class Thread
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:467: error: cannot find symbol
		return Thread.findScopedValueBindings();
		             ^
  symbol:   method findScopedValueBindings()
  location: class Thread
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:471: error: cannot find symbol
		Thread.setScopedValueBindings(scopeValueBindings);
		      ^
  symbol:   method setScopedValueBindings(Object)
  location: class Thread
.../openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:475: error: cannot find symbol
		Thread.ensureMaterializedForStackWalk(obj);
		      ^
  symbol:   method ensureMaterializedForStackWalk(Object)
  location: class Thread
```
Please help check whether everything is already included from your changes.

**Comment by ChengJin01** [comment]
It looks like it can't find these methods in openj9-openjdk-jdk-staging/src/java.base/share/classes/java/lang/Thread.java where they don't exist as compared to the code in JDK20.
e.g. 
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/0bbbf1b2b0400129ec718ecb62e988f2dd33d87e/src/java.base/share/classes/java/lang/Thread.java#L419
```
    @IntrinsicCandidate
    static native Object[] scopedValueCache();
```

**Comment by JasonFengJ9** [comment]
The `Merge-Openjdk-to-Master-JDKNext` job was disabled since the last merging conflict, hence no latest Thread update.
Just enabled it, currently there is [an infra issue](https://github.ibm.com/runtimes/infrastructure/issues/7700) pending.

**Comment by keithc-ca** [comment]
> @ChengJin01 a similar change as [ibmruntimes/openj9-openjdk-jdk20#12](https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12) is required here.
> 
> FYI @keithc-ca

@JasonFengJ9 To be clear, are you asking @ChengJin01 to create a pull request that extends this (like 
[jdk20#12](https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12)  extended [jdk20#9](https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/9))?

**Comment by JasonFengJ9** [comment]
> To be clear, are you asking @ChengJin01 to create a pull request that extends this (like
https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12 extended https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/9)?

That's correct.

**Comment by JasonFengJ9** [comment]
Updated with latest openjdk level `jdk-21+10`.

@ChengJin01  this can be used as the base for FFI JEP434 further OpenJ9 specific change.

**Comment by ChengJin01** [comment]
@JasonFengJ9, there is a compilation failure with your changes at `Access.java` as follows when compiling with my branch at https://github.com/ChengJin01/openj9-openjdk-jdk/tree/ffi_disable_java_code_in_compiling_jdknext_1:
```

/openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:69:
error: Access is not abstract and does not override abstract method getUTF16Char(byte[],int) in JavaLangAccess

final class Access implements JavaLangAccess {
      ^
```

**Comment by JasonFengJ9** [comment]
@ChengJin01 an OpenJ9 PR is created to add `JavaLangAccess.getUTF16Char()` & `countPositives()`
* https://github.com/eclipse-openj9/openj9/pull/16742

**Comment by keithc-ca** [comment]
There are some inappropriate changes here (e.g. that won't compile - double `{` in VaList.java); the ones I've noticed are addressed in #551.

**Comment by JasonFengJ9** [comment]
> e.g. that won't compile - double { in VaList.java);

Is the change introduced when resolving the merging conflict? Yeah, this PR won't compile w/o those FFI changes at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/551.

**Pull request merged**
