### PR TITLE
Fix Thread.stop if-condition typo

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
@tajila please take a look

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity alinux jdknext

**Comment by tajila** [comment]
Jenkins test sanity alinux64 jdknext

**Comment by pshipton** [comment]
Jenkins test sanity amac jdknext

**Comment by pshipton** [comment]
I stopped the alinux build, which was just waiting for a machine.

**Comment by tajila** [comment]
jenkins test sanity amac jdknext depends eclipse-openj9/openj9#15073

**Comment by tajila** [comment]
Those test failures are expected and tracked in https://github.com/eclipse-openj9/openj9/issues/15152

**Pull request merged**
