### PR TITLE
Add CRIU enablement flags

### PR DESCRIPTION
**Pull request by tajila**
Add CRIU enablement flags

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@keithc-ca Please review these changes

**Comment by keithc-ca** [comment]
Is the intent to support  CRIU in all Java versions (and pull requests for the other extension repos will follow shortly)?

**Comment by tajila** [comment]
> Is the intent to support CRIU in all Java versions (and pull requests for the other extension repos will follow shortly)?

Yes, I intend to open one for jdk8 and jdk11. I'm skipping jdk16 since 0.27 will be the last release.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins compile plinux jdknext

**Pull request merged**
