### PR TITLE
Clear vmthread from thread object at shutdown

### PR DESCRIPTION
**Pull request by tajila**
Related to: https://github.com/eclipse-openj9/openj9/issues/16659

### CODE REVIEW

**Comment by tajila** [comment]
@gacholio ^^

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdknext

**Comment by JasonFengJ9** [comment]
```
10:48:03  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_Personal/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:69: error: Access is not abstract and does not override abstract method ensureNativeAccess(Module,Class<?>,String) in JavaLangAccess
10:48:03  final class Access implements JavaLangAccess {
10:48:03        ^
10:48:03  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_Personal/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:399: error: method does not override or implement a method from a supertype
10:48:03  	@Override
10:48:03  	^
10:48:03  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_Personal/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:401: error: method ensureNativeAccess in class Module cannot be applied to given types;
10:48:03  		mod.ensureNativeAccess(clsOwner, methodName, clsCaller);
```

The latest openjdk updates are still in `openj9-staging` branch.

**Comment by gacholio** [comment]
Yes, this looks better.

**Comment by pshipton** [comment]
> The latest openjdk updates are still in openj9-staging branch, which is blocked by

It's also blocked by https://github.com/eclipse-openj9/openj9/issues/18321

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux64 jdknext

**Review by JasonFengJ9 — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Comment by keithc-ca** [comment]
The failures are known: https://github.com/eclipse-openj9/openj9/issues/18306.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
