### PR TITLE
Update copyrights

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
update

**Comment by groeges** [comment]
jenkins copyright check

**Comment by groeges** [comment]
jenkins copyright check

**Comment by groeges** [comment]
jenkins copyright check

**Comment by groeges** [comment]
jenkins copyright check

**Comment by groeges** [comment]
jenkins copyright check

**Comment by groeges** [comment]
jenkins copyright check

**Comment by andrew-m-leonard** [comment]
jenkins copyright check

**Pull request merged**
