### PR TITLE
Removed /r (CR) characters from module names in Modules.gmk

### PR DESCRIPTION
**Pull request by adam-thorpe**
Fixes: https://github.com/eclipse/openj9/issues/7248
FYI @andrew-m-leonard 

Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile win jdknext

**Comment by pshipton** [comment]
jenkins compile win jdknext

**Comment by pshipton** [comment]
@adam-thorpe note the copyright check is failing, pls add an IBM copyright

**Comment by adam-thorpe** [comment]
@pshipton done

**Comment by pshipton** [comment]
Will we be contributing this back to OpenJDK?

**Comment by pshipton** [comment]
jenkins compile win jdknext

**Comment by andrew-m-leonard** [comment]
@pshipton yes... https://github.ibm.com/runtimes/openjdk-contribution/issues/1057

**Pull request merged**
