### PR TITLE
Remove jdk.cmd man pages

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

### CODE REVIEW

**Comment by lumpfish** [comment]
Jenkins line endings check

**Comment by lumpfish** [comment]
Jenkins signed off by check

**Comment by lumpfish** [comment]
Jenkins copyright check

**Comment by keithc-ca** [comment]
Issue: eclipse/openj9#8732.

**Comment by keithc-ca** [comment]
@lumpfish I was prepared to merge this, but I was waiting for you to create a pull request for jdk14 so they could be merged at the same time. Is a jdk14 pull request imminent?

**Comment by lumpfish** [comment]
For jdk14: https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/48

**Pull request merged**
