### PR TITLE
Set scoped value bindings for newly-created thread

### PR DESCRIPTION
**Pull request by thallium**
Related:
- https://github.com/eclipse-openj9/openj9/pull/17402
- https://github.com/eclipse-openj9/openj9/issues/16677

### CODE REVIEW

**Comment by thallium** [comment]
@babsingh FYI

**Comment by babsingh** [comment]
@JasonFengJ9 @tajila Requesting your review. During adoption of OpenJDK's `java.lang.Thread`, we added a special `constructor` in `j.l.Thread` to support OpenJ9. This constructor is missing the initialization of the `scopedValueBindings` field. This change correctly initializes the `scopedValueBindings` field, prevents invocation of `Thread.findScopedValueBindings` where the assert gets triggered and allows us to pass a failing cert test reported in internal issue 149586.

**Comment by babsingh** [comment]
@thallium Can you confirm if your personal build with sanity.functional, sanity.openjdk and extended.openjdk test suites passed?

**Comment by thallium** [comment]
> @thallium Can you confirm if your personal build with sanity.functional, sanity.openjdk and extended.openjdk test suites passed?

Yes, see https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34375/ https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34377/ https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34378/. All the test failure is known test failure.

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Comment by JasonFengJ9** [comment]
Jenkins test sanity amac jdknext

**Comment by JasonFengJ9** [comment]
@tajila please merge if you approve assuming the PR build passes.

**Review by tajila — APPROVED** [review]

**Pull request merged**
