### PR TITLE
Set vm.bits property

### PR DESCRIPTION
**Pull request by sophia-guo**
Set vm.bits property to be available in the @requires expressions

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Related with #245

**Comment by sophia-guo** [comment]
@pshipton updated.

**Comment by pshipton** [comment]
jenkins line endings check

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdknext

**Comment by pshipton** [comment]
jenkins test sanity.openjdk zlinux jdknext

**Comment by pshipton** [comment]
The test failures are expected.

**Pull request merged**
