### PR TITLE
Fix compile issues with xlc on AIX

### PR DESCRIPTION
**Pull request by keithc-ca**
Revert ["8327701: Remove the xlc toolchain"](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ceeb8571963012d55755ad7d875b5fedb93e7db1).

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins compile aix jdknext

**Comment by keithc-ca** [comment]
Not sure why this is happening
```
[2024-03-15T22:03:04.487Z] /opt/freeware/bin/bash: line 1: 29622706 Illegal instruction     (core dumped) /home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk/bin/javac -g -Xlint:all -source 23 -target 23 -implicit:none -Xprefer:source -XDignore.symbol.file=true -encoding ascii -Werror --add-modules jdk.compiler,jdk.jdeps --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -Xlint:-options,-this-escape -XDmodifiedInputs=/home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.modfiles.fixed -d /home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/create_symbols_javac @/home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.filelist > >(/opt/freeware/bin/tee -a /home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.log) 2> >(/opt/freeware/bin/tee -a /home/jenkins/workspace/Build_JDKnext_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.log >&2)
```

**Comment by keithc-ca** [comment]
Jenkins compile aix jdknext

**Comment by keithc-ca** [comment]
The "Illegal instruction" instruction was due to the unwanted link option `-bnorwexec`.

**Comment by keithc-ca** [comment]
Jenkins compile aix jdknext

**Comment by pshipton** [comment]
jenkins compile amac,xmac,plinux jdknext

**Review by pshipton — APPROVED** [review]

**Pull request merged**
