### PR TITLE
Update the ignore list based on RC1 build

### PR DESCRIPTION
**Pull request by JinhangZhang**
Update the ignore list based on RC1 results among various platforms.

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@jasonkatonica @llxia FYI

**Comment by keithc-ca** [comment]
Jenkins test sanity jdknext

**Comment by llxia** [comment]
The above [PR build](https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDKnext/301/) failed due to `ERROR: Pull Request trigger comment needs to specify TESTS_TARGET, PLATFORM and SDK_VERSION`.  

Even if the PR build command is set correctly, the file `ProblemList-FIPS140_3_OpenJcePlus.txt` is a special problem list for FIPS and won’t be used by the test pipeline unless the FIPS `TEST_FLAG` is explicitly set. At the moment, I don't believe our PR test builds support `TEST_FLAG`. To properly test this PR, Grinder should be used.

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux jdknext

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
